# Generated by Django 4.2.13 on 2024-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("my_app", "0002_members_joined_date_members_phone")]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("email", models.CharField(max_length=225)),
                ("password", models.CharField(max_length=225)),
            ],
        )
    ]
