# Generated by Django 4.2.13 on 2024-07-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_post_created_by_alter_post_updated_by_and_more")
    ]

    operations = [migrations.AlterModelTable(name="board", table="new_Board")]
